#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Mar  2 09:37:13 2022

@author: yannick
"""

from binance.client import Client
import time

api_key = ""
api_secret = ""
binance_client = Client(api_key, api_secret)
eth_newprice = float(binance_client.futures_symbol_ticker(symbol='ETHUSDT')['price'])
eth_prevprice = eth_newprice
wallet = True

while True :
    try :
        eth_newprice = float(binance_client.futures_symbol_ticker(symbol='ETHUSDT')['price'])

        if eth_prevprice > eth_newprice*1.003 and wallet == True:
            time.sleep(180)
            if eth_prevprice > eth_newprice*1.01:
                time.sleep(180)
                if eth_prevprice > eth_newprice*1.0015:
                    binance_client.futures_create_order(symbol='ETHUSDT',type='MARKET',side='BUY',quantity=0.06)
                    wallet = False
                    print("buy")
                    eth_prevprice = eth_newprice
        elif eth_newprice*1.001 < eth_prevprice and wallet==True:
            binance_client.futures_create_order(symbol='ETHUSDT',type='MARKET',side='BUY',quantity=0.06)
            wallet = False
            print("buy")
        elif eth_newprice > eth_prevprice*1.0015 and wallet==False:
            binance_client.futures_create_order(symbol='ETHUSDT',type='MARKET',side='SELL',quantity=0.06)
            wallet = True
            print("sell")
        elif eth_newprice > eth_prevprice and wallet==True:
            eth_prevprice = eth_newprice
        time.sleep(60)

    except KeyboardInterrupt:
        if wallet == False:
            while eth_newprice < eth_prevprice*1.001:
                eth_newprice = float(binance_client.futures_symbol_ticker(symbol='ETHUSDT')['price'])
            binance_client.futures_create_order(symbol='ETHUSDT',type='MARKET',side='SELL',quantity=0.1)
        break
    
#https://www.binance.com/en/trade/ETH_BUSD?layout=pro
